import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: true,
  outDir: 'dist',
  splitting: false,
  clean: true,
  // Don't bundle any dependencies - treat as a library
  noExternal: [],
  // Mark all dependencies as external
  external: [
    // All your dependencies should be external
    '@azure/app-configuration',
    '@azure/core-auth',
    '@azure/openai',
    '@azure/storage-blob',
    '@langchain/community',
    '@langchain/core',
    '@langchain/openai',
    'csv-parse',
    'dotenv',
    'exceljs',
    'mssql',
    'nodemailer',
    'openai',
    'pdf-lib',
    'pdf-parse',
    'zod',
    // Node.js built-ins
    'ws',
    'events',
    'fs',
    'net',
    'tls',
    'zlib',
    'stream',
    'path',
    'crypto',
    'http',
    'https',
    'url',
    'querystring',
    'buffer',
    'util',
    'os',
    'child_process',
    'cluster',
    'dgram',
    'dns',
    'domain',
    'module',
    'process',
    'punycode',
    'readline',
    'repl',
    'string_decoder',
    'sys',
    'timers',
    'tty',
    'v8',
    'vm',
    'worker_threads',
  ],
  treeshake: true,
  minify: false,
  sourcemap: true,
  platform: 'node',
  target: 'node18',
});
