name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js with caching for npm dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build your TypeScript project (compiles to dist/)
      - name: Build
        run: npm run build

      # (Optional) Run tests if you have any
     # - name: Run tests
      #  run: npm test

  publish:
    needs: build
    runs-on: ubuntu-latest
    # Only run publish when a tag is pushed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for Publishing
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
